// Biome + patch definitions. Each planet picks 4 biomes; each biome is home to one
// creature and is packed with small named "patches" that complete with their own ping.
//
// Patch shapes: 'blob' (organic circle, r in radians) or 'path' (wandering trail).
// water: patch fills with water when completed. emissive: restored patch glows.
// props: [kind, density per vertex, place ('any' | 'rim' | 'inner')]
// critters: [kind, count] spawned when the patch / biome is restored.
// finds: collectibles rolled when a patch completes. rarity c(ommon) / r(are) / l(egendary).
// particles: ambient motes drifting around you [colours, gravity (negative rises), rate/sec]

const S = { r: [0.06, 0.08] }; // small: one swipe
const M = { r: [0.09, 0.12] }; // medium
const L = { r: [0.12, 0.15] }; // large

export const BIOMES = {
  meadow: {
    name: 'Bunny Meadow', creature: 'bunny', weight: 0.12, terrain: 'rolling',
    dead: 0x6d6a5a, alive: 0x72d35a, sky: ['#8c9ee6', '#ffe8d4'], style: [0, 0, 0],
    small: [['grass', 0.12], ['flower', 0.04], ['pebble', 0.004]],
    big: [['tree', 0.004]],
    critters: [['butterfly', 4], ['bird', 2]],
    particles: [[0xfff3a0, 0xffffff], -0.6, 6],
    patches: [
      { name: 'Flower bed', shape: 'blob', ...M, dead: 0x564a48, alive: 0x8fe070, props: [['tulip', 0.5]], critters: [['butterfly', 2]] },
      { name: 'Old dirt road', shape: 'path', dead: 0x857a70, alive: 0xdcc59a, props: [['pathStone', 0.12], ['lantern', 0.025, 'rim']] },
      { name: 'Little orchard', shape: 'blob', ...L, dead: 0x635a5e, alive: 0x5fc24f, props: [['appleTree', 0.05]], critters: [['bird', 1]] },
      { name: 'Beehive', shape: 'blob', ...S, dead: 0x6a5d4a, alive: 0xb8e05a, props: [['beehive', 0.03, 'inner'], ['flower', 0.3]], critters: [['bee', 3]] },
      { name: 'Hay field', shape: 'blob', ...M, dead: 0x7a705a, alive: 0xe8d57a, props: [['haybale', 0.05]] },
      { name: 'Sunflower row', shape: 'path', dead: 0x6a6450, alive: 0x9adf6a, props: [['sunflower', 0.25, 'rim']], critters: [['bee', 1]] },
    ],
    patchCount: 10,
    finds: [['🌼', 'Daisy', 'c'], ['🐞', 'Ladybug', 'c'], ['🌷', 'Tulip', 'c'], ['🐝', 'Bumblebee', 'c'], ['🌻', 'Sunflower', 'r'], ['🍯', 'Honey pot', 'r'], ['🪺', 'Bird nest', 'r'], ['🍀', 'Four-leaf clover', 'l']],
  },
  pond: {
    name: 'Sleepy Pond', creature: 'frog', weight: -0.12, terrain: 'basin',
    dead: 0x5e5048, alive: 0x4fbf86, sky: ['#7fa9e0', '#d4f7ea'], style: [0, 0, 0],
    small: [['grass', 0.1], ['reed', 0.008], ['pebble', 0.006]],
    big: [['reed', 0.006], ['willow', 0.002]],
    critters: [['dragonfly', 4], ['fish', 3]],
    particles: [[0x9ff0ff, 0xd0ffd0], -0.3, 5],
    patches: [
      { name: 'The pond', shape: 'blob', center: true, rFrac: 0.5, water: 0x3aa6c9, dead: 0x4d4038, alive: 0x3f9f7a, props: [['lily', 0.08, 'inner'], ['reed', 0.05, 'rim']], critters: [['fish', 3], ['dragonfly', 2]] },
      { name: 'Reed bank', shape: 'blob', ...S, dead: 0x5a5148, alive: 0x5fb36a, props: [['reed', 0.35]], critters: [['dragonfly', 1]] },
      { name: 'Lily cove', shape: 'blob', ...M, water: 0x4ab8c0, dead: 0x4f443c, alive: 0x4aa880, props: [['lily', 0.2, 'inner']], critters: [['fish', 1]] },
      { name: 'Mossy rocks', shape: 'blob', ...S, dead: 0x5c5650, alive: 0x5aa860, props: [['mossRock', 0.12]] },
      { name: 'Frog log', shape: 'blob', ...S, dead: 0x5a4e46, alive: 0x6ab86a, props: [['log', 0.03, 'inner'], ['shroom', 0.1]] },
      { name: 'Willow bend', shape: 'blob', ...M, dead: 0x554c46, alive: 0x5fbf7a, props: [['willow', 0.03]] },
    ],
    patchCount: 7,
    finds: [['🪷', 'Lotus', 'c'], ['🐟', 'Minnow', 'c'], ['🪨', 'Smooth pebble', 'c'], ['🪲', 'Water beetle', 'c'], ['🦆', 'Duckling', 'r'], ['🐠', 'Koi', 'r'], ['🦢', 'Swan', 'r'], ['🦪', 'Pond pearl', 'l']],
  },
  desert: {
    name: 'Dusty Dunes', creature: 'fox', weight: 0.02, terrain: 'dunes',
    dead: 0x9c8b74, alive: 0xf2cf86, sky: ['#c48fb8', '#ffe4c4'], style: [1, 0, 0],
    small: [['shrub', 0.012], ['desertRock', 0.008]],
    big: [['cactus', 0.006]],
    critters: [['bird', 3]],
    particles: [[0xf5d9a0, 0xe0b880], 0.4, 8],
    patches: [
      { name: 'Oasis', shape: 'blob', ...M, water: 0x2fd6c6, dead: 0x6f6158, alive: 0x7fcf6a, props: [['palm', 0.05, 'rim']], critters: [['bird', 1]] },
      { name: 'Cactus garden', shape: 'blob', ...M, dead: 0x7d6e66, alive: 0xe8c478, props: [['cactus', 0.09]] },
      { name: 'Dune trail', shape: 'path', dead: 0x9a8f86, alive: 0xffe0a0, props: [['desertRock', 0.06, 'rim']] },
      { name: 'Sandstone arch', shape: 'blob', ...S, dead: 0x8a7a6a, alive: 0xf0b070, props: [['arch', 0.02, 'inner']] },
      { name: 'Desert bloom', shape: 'blob', ...S, dead: 0x86786c, alive: 0xd8c070, props: [['flower', 0.35], ['cactus', 0.03]], critters: [['butterfly', 1]] },
      { name: 'Old ruins', shape: 'blob', ...M, dead: 0x7e7064, alive: 0xe0c090, props: [['pillar', 0.06]] },
    ],
    patchCount: 8,
    finds: [['🪶', 'Feather', 'c'], ['🦂', 'Scorpion', 'c'], ['🐍', 'Sand snake', 'c'], ['🌵', 'Cactus fruit', 'c'], ['🏺', 'Old vase', 'r'], ['🦴', 'Fossil', 'r'], ['🐪', 'Camel', 'r'], ['👑', 'Lost crown', 'l']],
  },
  snow: {
    name: 'Frosty Peaks', creature: 'penguin', weight: 0.04, terrain: 'peaks',
    dead: 0x8690a8, alive: 0xd5dfee, sky: ['#8fa0dc', '#eef4ff'], style: [0, 1, 0],
    small: [['snowdrop', 0.02], ['crystal', 0.005]],
    big: [['pine', 0.006]],
    critters: [['bird', 3]],
    particles: [[0xffffff, 0xe0f0ff], 0.8, 14],
    patches: [
      { name: 'Frozen lake', shape: 'blob', ...M, water: 0xbfe9ff, dead: 0x6a6c78, alive: 0xdff2ff, props: [['crystal', 0.06, 'rim']] },
      { name: 'Pine grove', shape: 'blob', ...L, dead: 0x6f707c, alive: 0xd0dcec, props: [['pine', 0.07]], critters: [['bird', 1]] },
      { name: 'Snowman hill', shape: 'blob', ...S, dead: 0x767884, alive: 0xdde6f2, props: [['snowman', 0.04]] },
      { name: 'Sled run', shape: 'path', dead: 0x8a8d99, alive: 0xd6ecff, props: [['lantern', 0.03, 'rim']] },
      { name: 'Igloo', shape: 'blob', ...S, dead: 0x7a7e8c, alive: 0xe6eef8, props: [['igloo', 0.02, 'inner'], ['crystal', 0.05, 'rim']] },
      { name: 'Ice spires', shape: 'blob', ...M, dead: 0x6e7484, alive: 0xc8e0f4, props: [['iceSpire', 0.06]] },
    ],
    patchCount: 8,
    finds: [['❄️', 'Snowflake', 'c'], ['🧤', 'Lost mitten', 'c'], ['🧣', 'Scarf', 'c'], ['🫐', 'Frost berries', 'c'], ['⛸️', 'Ice skate', 'r'], ['🦭', 'Seal pup', 'r'], ['🦌', 'Reindeer', 'r'], ['💠', 'Ice heart', 'l']],
  },
  grove: {
    name: 'Moonlit Grove', creature: 'moth', weight: -0.04, terrain: 'hillocks',
    dead: 0x433c52, alive: 0x6a58cc, sky: ['#8a78d8', '#ffcdea'], style: [0, 0, 1],
    small: [['fern', 0.03], ['glowShroom', 0.012]],
    big: [['glowShroom', 0.02], ['moonTree', 0.003]],
    critters: [['firefly', 10]],
    particles: [[0xd0ff80, 0xa0ffe0], -0.2, 6],
    patches: [
      { name: 'Mushroom ring', shape: 'blob', ...M, dead: 0x413c4c, alive: 0x5a48b8, props: [['glowShroom', 0.25, 'rim']], critters: [['firefly', 3]] },
      { name: 'Firefly path', shape: 'path', dead: 0x5a5466, alive: 0x9f8cff, props: [['glowStone', 0.08, 'rim']], critters: [['firefly', 4]] },
      { name: 'Fern hollow', shape: 'blob', ...M, dead: 0x46414f, alive: 0x4fa88a, props: [['fern', 0.35]] },
      { name: 'Moonflower patch', shape: 'blob', ...S, dead: 0x48425a, alive: 0x7a6ad8, props: [['moonflower', 0.4]], critters: [['moth', 2]] },
      { name: 'Crystal spire', shape: 'blob', ...S, dead: 0x4a4458, alive: 0x8a70e0, props: [['bigCrystal', 0.03, 'inner'], ['crystal', 0.1, 'rim']] },
      { name: 'Moon trees', shape: 'blob', ...L, dead: 0x3f3a4a, alive: 0x5a4ab0, props: [['moonTree', 0.04]], critters: [['firefly', 2]] },
    ],
    patchCount: 8,
    finds: [['🍄', 'Glowcap', 'c'], ['🪻', 'Moonflower', 'c'], ['🕯️', 'Candle', 'c'], ['🌿', 'Silver fern', 'c'], ['🌙', 'Moonstone', 'r'], ['🦉', 'Owl', 'r'], ['🔮', 'Crystal ball', 'r'], ['🧚', 'Fairy', 'l']],
  },
  garden: {
    name: 'Snail Garden', creature: 'snail', weight: 0.06, terrain: 'gentle',
    dead: 0x6e6256, alive: 0x9ad46a, sky: ['#86aed6', '#fff0dc'], style: [0, 0, 0],
    small: [['grass', 0.1], ['flower', 0.05]],
    big: [['bush', 0.006]],
    critters: [['butterfly', 3], ['bird', 2], ['bee', 2]],
    particles: [[0xffb0d0, 0xffffff], 0.25, 5],
    patches: [
      { name: 'Rose garden', shape: 'blob', ...M, dead: 0x5c5250, alive: 0x7cc45a, props: [['bush', 0.12]], critters: [['butterfly', 2]] },
      { name: 'Stepping stones', shape: 'path', dead: 0x7a7470, alive: 0xb7e08a, props: [['pathStone', 0.14]] },
      { name: 'Old oak', shape: 'blob', ...S, dead: 0x5e5752, alive: 0x6cba4f, props: [['bigOak', 0.012, 'inner'], ['shroom', 0.1, 'rim']], critters: [['bird', 1]] },
      { name: 'Veggie patch', shape: 'blob', ...M, dead: 0x5a4a40, alive: 0x6a4a34, props: [['cabbage', 0.15], ['carrot', 0.15]] },
      { name: 'Birdbath', shape: 'blob', ...S, dead: 0x6a625a, alive: 0x8acc6a, props: [['birdbath', 0.02, 'inner'], ['flower', 0.3]], critters: [['bird', 2]] },
      { name: 'Gnome corner', shape: 'blob', ...S, dead: 0x645a54, alive: 0x90d070, props: [['gnome', 0.04], ['shroom', 0.08]] },
    ],
    patchCount: 9,
    finds: [['🥕', 'Carrot', 'c'], ['🥬', 'Cabbage', 'c'], ['🍓', 'Strawberry', 'c'], ['🐛', 'Caterpillar', 'c'], ['🌹', 'Rose', 'r'], ['🐦', 'Robin', 'r'], ['🪴', 'Potted fern', 'r'], ['🍉', 'Prize melon', 'l']],
  },
  shore: {
    name: 'Sunny Shore', creature: 'turtle', weight: 0.02, terrain: 'beach',
    dead: 0x8e8676, alive: 0xf5dfa6, sky: ['#6fb0dd', '#ffecc8'], style: [1, 0, 0],
    small: [['shell', 0.01], ['seaGrass', 0.01]],
    big: [['palm', 0.004]],
    critters: [['crab', 4], ['fish', 2], ['bird', 2]],
    particles: [[0xffffff, 0xbff4ff], -0.4, 6],
    patches: [
      { name: 'Lagoon', shape: 'blob', center: true, rFrac: 0.45, water: 0x3fd8e0, dead: 0x5e5a50, alive: 0xe8d6a0, props: [['coral', 0.06, 'inner'], ['palm', 0.04, 'rim']], critters: [['fish', 3]] },
      { name: 'Shell beach', shape: 'blob', ...M, dead: 0x8a8272, alive: 0xffe8b8, props: [['shell', 0.25]], critters: [['crab', 1]] },
      { name: 'Starfish shallows', shape: 'blob', ...S, water: 0x5ae0e0, dead: 0x6e685c, alive: 0xf0d8a0, props: [['starfish', 0.2]] },
      { name: 'Sandcastle', shape: 'blob', ...S, dead: 0x8a8272, alive: 0xf8e0a8, props: [['sandcastle', 0.025, 'inner'], ['shell', 0.1, 'rim']] },
      { name: 'Coral garden', shape: 'blob', ...M, dead: 0x7a7266, alive: 0xf0c8a0, props: [['coral', 0.15]], critters: [['crab', 1]] },
      { name: 'Boardwalk', shape: 'path', dead: 0x857d70, alive: 0xc89a68, props: [['plank', 0.2]] },
    ],
    patchCount: 8,
    finds: [['🐚', 'Seashell', 'c'], ['⭐', 'Starfish', 'c'], ['🦀', 'Hermit crab', 'c'], ['🦐', 'Shrimp', 'c'], ['🪸', 'Coral', 'r'], ['🐙', 'Octopus', 'r'], ['🐬', 'Dolphin', 'r'], ['🗝️', 'Treasure key', 'l']],
  },
  volcano: {
    name: 'Ember Crags', creature: 'lizard', weight: 0, terrain: 'volcano',
    dead: 0x4a4448, alive: 0x6e3a30, sky: ['#c47a9a', '#ffd8bf'], style: [0, 0, 0],
    small: [['lavaRock', 0.01], ['fireFlower', 0.01]],
    big: [['obsidian', 0.006]],
    critters: [['ember', 8]],
    particles: [[0xff8a30, 0xffc040], -1.2, 14],
    patches: [
      { name: 'Lava lake', shape: 'blob', center: true, rFrac: 0.22, water: 0xff6a1a, emissive: 1, dead: 0x3a3436, alive: 0x5a2a22, props: [['lavaRock', 0.08, 'rim']], critters: [['ember', 3]] },
      { name: 'Lava river', shape: 'path', water: 0xff7a2a, emissive: 1, dead: 0x3e3a3c, alive: 0x6a3020, props: [['lavaRock', 0.05, 'rim']] },
      { name: 'Fire flowers', shape: 'blob', ...M, dead: 0x464044, alive: 0x7a3a2a, props: [['fireFlower', 0.35]], critters: [['ember', 2]] },
      { name: 'Obsidian field', shape: 'blob', ...M, dead: 0x403a40, alive: 0x4a3048, props: [['obsidian', 0.1]] },
      { name: 'Dragon nest', shape: 'blob', ...S, dead: 0x4a4246, alive: 0x8a5a3a, props: [['dragonEgg', 0.04, 'inner'], ['haybale', 0.03, 'rim']] },
      { name: 'Ember vents', shape: 'blob', ...S, dead: 0x443e42, alive: 0x6a2a20, emissive: 0.5, props: [['vent', 0.05]], critters: [['ember', 2]] },
    ],
    patchCount: 8,
    finds: [['🔥', 'Ember', 'c'], ['🌶️', 'Fire pepper', 'c'], ['🪙', 'Molten coin', 'c'], ['⚱️', 'Ash urn', 'c'], ['🌋', 'Tiny volcano', 'r'], ['☄️', 'Meteorite', 'r'], ['💎', 'Fire gem', 'r'], ['🥚', 'Dragon egg', 'l']],
  },
  candy: {
    name: 'Sugar Hills', creature: 'bear', weight: 0.02, terrain: 'bumps',
    dead: 0x7a6f78, alive: 0xffa8d0, sky: ['#c48ad8', '#d4e8ff'], style: [0, 0.6, 0],
    small: [['gumdrop', 0.008], ['sprinkle', 0.04]],
    big: [['lollipop', 0.005]],
    critters: [['butterfly', 4], ['bee', 2]],
    particles: [[0xff8fd0, 0x8fe8ff, 0xfff080], -0.4, 8],
    patches: [
      { name: 'Lollipop lane', shape: 'path', dead: 0x7e7480, alive: 0xfff0f6, props: [['lollipop', 0.06, 'rim']] },
      { name: 'Gumdrop grove', shape: 'blob', ...M, dead: 0x766c76, alive: 0xff9ac8, props: [['gumdrop', 0.25]] },
      { name: 'Cupcake corner', shape: 'blob', ...S, dead: 0x786e76, alive: 0xffc0dc, props: [['cupcake', 0.08]] },
      { name: 'Candy cane forest', shape: 'blob', ...M, dead: 0x6e6670, alive: 0xffb8d8, props: [['candyCane', 0.08]] },
      { name: 'Chocolate pond', shape: 'blob', ...M, water: 0x8a5232, dead: 0x6a5a5a, alive: 0xff9ac0, props: [['gumdrop', 0.08, 'rim']] },
      { name: 'Donut den', shape: 'blob', ...S, dead: 0x746a72, alive: 0xffd0e4, props: [['donut', 0.06]] },
    ],
    patchCount: 8,
    finds: [['🍭', 'Lollipop', 'c'], ['🍬', 'Sweetie', 'c'], ['🧁', 'Cupcake', 'c'], ['🍪', 'Cookie', 'c'], ['🍩', 'Donut', 'r'], ['🍫', 'Chocolate bar', 'r'], ['🎂', 'Birthday cake', 'r'], ['🌈', 'Rainbow drop', 'l']],
  },
  autumn: {
    name: 'Maple Hollow', creature: 'hedgehog', weight: 0.08, terrain: 'rolling',
    dead: 0x6a625c, alive: 0xd98a3a, sky: ['#b88aa8', '#ffe6cf'], style: [0, 0, 0],
    small: [['leafPile', 0.008], ['shroom', 0.006], ['grass', 0.04]],
    big: [['maple', 0.003]],
    critters: [['bird', 3], ['butterfly', 2]],
    particles: [[0xff8a30, 0xffc040, 0xe05030], 0.5, 8],
    patches: [
      { name: 'Maple grove', shape: 'blob', ...L, dead: 0x5e5650, alive: 0xc87830, props: [['maple', 0.045]], critters: [['bird', 1]] },
      { name: 'Pumpkin patch', shape: 'blob', ...M, dead: 0x5e5048, alive: 0x7a5a30, props: [['pumpkin', 0.12]] },
      { name: 'Leaf piles', shape: 'blob', ...S, dead: 0x645c56, alive: 0xe0903a, props: [['leafPile', 0.2]] },
      { name: 'Apple orchard', shape: 'blob', ...M, dead: 0x5c5650, alive: 0x9ab04a, props: [['appleTree', 0.06]], critters: [['bird', 1]] },
      { name: 'Mushroom log', shape: 'blob', ...S, dead: 0x5a524e, alive: 0xb8702e, props: [['log', 0.03, 'inner'], ['shroom', 0.15]] },
      { name: 'Forest trail', shape: 'path', dead: 0x746a62, alive: 0xb08a5a, props: [['pathStone', 0.1], ['lantern', 0.02, 'rim']] },
    ],
    patchCount: 9,
    finds: [['🍂', 'Fallen leaf', 'c'], ['🌰', 'Chestnut', 'c'], ['🎃', 'Pumpkin', 'c'], ['🍎', 'Apple', 'c'], ['🐿️', 'Squirrel', 'r'], ['🧺', 'Picnic basket', 'r'], ['🥧', 'Apple pie', 'r'], ['🍁', 'Golden maple', 'l']],
  },
};


// ---------------------------------------------------------------- Citylight galaxy
// Abandoned grey streets that light back up: windows glow, awnings unfurl, the traffic returns.
// style[3] = paved: restored ground shows paving-slab seams.

Object.assign(BIOMES, {
  park: {
    name: 'Plaza Park', creature: 'squirrel', weight: 0.1, terrain: 'gentle',
    dead: 0x6a6670, alive: 0x7fd36a, sky: ['#8fa8f0', '#ffe6d0'], style: [0, 0, 0, 0.25],
    small: [['grass', 0.1], ['flower', 0.03]],
    big: [['parkTree', 0.004]],
    critters: [['bird', 3], ['butterfly', 2]],
    particles: [[0xffffff, 0xfff3a0], -0.5, 5],
    patches: [
      { name: 'Fountain square', shape: 'blob', center: true, rFrac: 0.3, dead: 0x77727a, alive: 0xe8dcc8, pave: 1, props: [['fountain', 0.012, 'inner'], ['bench', 0.04, 'rim'], ['lampPost', 0.025, 'rim']], critters: [['bird', 2]] },
      { name: 'Flower beds', shape: 'blob', ...M, dead: 0x5e5658, alive: 0x8fe070, props: [['planter', 0.08], ['flower', 0.3]], critters: [['butterfly', 2]] },
      { name: 'Tree-lined avenue', shape: 'path', dead: 0x807a78, alive: 0xdcd2c2, pave: 1, props: [['parkTree', 0.03, 'rim'], ['lampPost', 0.015, 'rim']] },
      { name: 'Picnic lawn', shape: 'blob', ...L, dead: 0x635e5a, alive: 0x74d060, props: [['grass', 0.3], ['bench', 0.02, 'rim']] },
      { name: 'Hot dog corner', shape: 'blob', ...S, dead: 0x726c70, alive: 0xe6d8c0, pave: 1, props: [['hotdogCart', 0.04, 'inner'], ['bench', 0.05, 'rim']] },
      { name: 'Hedge maze', shape: 'blob', ...M, dead: 0x5a5a52, alive: 0x6cc85a, props: [['hedge', 0.12]] },
    ],
    patchCount: 10,
    finds: [['🥨', 'Pretzel', 'c'], ['🌭', 'Hot dog', 'c'], ['🎈', 'Red balloon', 'c'], ['🥜', 'Peanuts', 'c'], ['🪁', 'Kite', 'r'], ['🛹', 'Skateboard', 'r'], ['🥏', 'Frisbee', 'r'], ['⛲', 'Wishing fountain', 'l']],
  },
  downtown: {
    name: 'Neon Downtown', creature: 'cat', weight: 0.06, terrain: 'city',
    dead: 0x5e5a68, alive: 0xb8b0d8, sky: ['#5a4f9a', '#ffb8d8'], style: [0, 0, 0.15, 0.9],
    small: [['hydrant', 0.003]],
    big: [['tower', 0.006]],
    critters: [['firefly', 4], ['bird', 2]],
    particles: [[0xff8fd8, 0x8fd8ff, 0xfff3a0], -0.4, 6],
    patches: [
      { name: 'Skyscraper block', shape: 'blob', ...L, dead: 0x5a5664, alive: 0xc8c0e0, pave: 1, props: [['tower', 0.06, 'inner']] },
      { name: 'Main street', shape: 'path', dead: 0x55525e, alive: 0x8a86a0, pave: 1, props: [['car', 0.03], ['trafficLight', 0.015, 'rim'], ['lampPost', 0.02, 'rim']] },
      { name: 'Shopping row', shape: 'blob', ...M, dead: 0x5e5a66, alive: 0xd8c8e0, pave: 1, props: [['shopFront', 0.05]] },
      { name: 'Billboard corner', shape: 'blob', ...S, dead: 0x5a5662, alive: 0xc0b8e0, pave: 1, props: [['billboard', 0.04, 'inner'], ['hydrant', 0.03, 'rim']] },
      { name: 'Neon alley', shape: 'path', emissive: 0.35, dead: 0x4e4a58, alive: 0xb090e0, pave: 1, props: [['neonSign', 0.05, 'rim']], critters: [['firefly', 2]] },
      { name: 'Pocket plaza', shape: 'blob', ...S, dead: 0x625e6a, alive: 0xe0d6e8, pave: 1, props: [['bench', 0.05], ['planter', 0.05]] },
    ],
    patchCount: 10,
    finds: [['☕', 'Coffee cup', 'c'], ['🍕', 'Pizza slice', 'c'], ['🚕', 'Taxi', 'c'], ['🗞️', 'Newspaper', 'c'], ['🎧', 'Headphones', 'r'], ['🎭', 'Theatre masks', 'r'], ['🎷', 'Saxophone', 'r'], ['🌃', 'Neon skyline', 'l']],
  },
  suburbs: {
    name: 'Sleepy Suburbs', creature: 'dog', weight: 0.12, terrain: 'gentle',
    dead: 0x6c6a5c, alive: 0x86d86a, sky: ['#9fb6f0', '#ffe9c8'], style: [0, 0, 0, 0],
    small: [['grass', 0.12], ['flower', 0.04]],
    big: [['house', 0.004]],
    critters: [['butterfly', 3], ['bird', 2]],
    particles: [[0xffffff, 0xfff8d0], -0.3, 5],
    patches: [
      { name: 'Cul-de-sac', shape: 'blob', ...L, dead: 0x6a6664, alive: 0x8ad46e, props: [['house', 0.03, 'inner'], ['bush', 0.04, 'rim']] },
      { name: 'Picket fence lane', shape: 'path', dead: 0x7c766e, alive: 0xd8ccb8, pave: 0.6, props: [['fence', 0.1, 'rim'], ['mailbox', 0.02, 'rim']] },
      { name: 'Front garden', shape: 'blob', ...M, dead: 0x5e584e, alive: 0x92e070, props: [['gnome', 0.03], ['flower', 0.3], ['bush', 0.05]] },
      { name: 'Backyard pool', shape: 'blob', ...S, dead: 0x625e54, alive: 0x7ad86a, props: [['paddlingPool', 0.03, 'inner'], ['grass', 0.2]] },
      { name: 'Driveway', shape: 'blob', ...S, dead: 0x6e6a6c, alive: 0xc8c4c0, pave: 1, props: [['car', 0.04, 'inner']] },
      { name: 'Hedge row', shape: 'path', dead: 0x5c5a50, alive: 0x70c860, props: [['hedge', 0.06, 'rim']] },
    ],
    patchCount: 10,
    finds: [['🦴', 'Dog bone', 'c'], ['🎾', 'Tennis ball', 'c'], ['🍪', 'Cookie', 'c'], ['🥛', 'Milk bottle', 'c'], ['🧸', 'Teddy bear', 'r'], ['🛼', 'Roller skate', 'r'], ['🪀', 'Yo-yo', 'r'], ['🏆', 'Best in show', 'l']],
  },
  funfair: {
    name: 'Funfair Pier', creature: 'raccoon', weight: 0.04, terrain: 'beach',
    dead: 0x6a6460, alive: 0xe8c89a, sky: ['#a88ae8', '#ffd2a8'], style: [0.2, 0, 0, 0.3],
    small: [['balloons', 0.002]],
    big: [['ferrisWheel', 0.0012]],
    critters: [['bird', 2]],
    particles: [[0xff8fc4, 0xffe14d, 0x8fd8ff, 0xb4ff86], 0.35, 8],
    patches: [
      { name: 'Ferris wheel', shape: 'blob', center: true, rFrac: 0.28, dead: 0x6e6862, alive: 0xf0d8b0, pave: 0.6, props: [['ferrisWheel', 0.01, 'inner'], ['balloons', 0.03, 'rim']] },
      { name: 'Carousel', shape: 'blob', ...M, dead: 0x6a645e, alive: 0xf0d0b8, pave: 0.6, props: [['carousel', 0.02, 'inner'], ['bunting', 0.03, 'rim']] },
      { name: 'Food stalls', shape: 'path', dead: 0x746c66, alive: 0xe8c8a0, props: [['stall', 0.04, 'rim'], ['balloons', 0.015]] },
      { name: 'Boardwalk', shape: 'path', dead: 0x6e665e, alive: 0xd8b088, props: [['plank', 0.05], ['lampPost', 0.02, 'rim']] },
      { name: 'Balloon stand', shape: 'blob', ...S, dead: 0x6a6460, alive: 0xf0d8c0, props: [['balloons', 0.12]] },
      { name: 'Bunting square', shape: 'blob', ...S, dead: 0x6e6862, alive: 0xf4dcb8, pave: 0.6, props: [['bunting', 0.08]] },
    ],
    patchCount: 10,
    finds: [['🍿', 'Popcorn', 'c'], ['🍦', 'Ice cream', 'c'], ['🎟️', 'Ride ticket', 'c'], ['🥤', 'Fizzy pop', 'c'], ['🎯', 'Bullseye', 'r'], ['🎠', 'Carousel horse', 'r'], ['🎪', 'Big top', 'r'], ['🎫', 'Golden ticket', 'l']],
  },
  harbour: {
    name: 'Dockside Harbour', creature: 'seagull', weight: -0.06, terrain: 'basin',
    dead: 0x5c6068, alive: 0x9ab8c8, sky: ['#7fa8e8', '#ffe0d0'], style: [0, 0, 0, 0.6],
    small: [['bollard', 0.004]],
    big: [['crane', 0.003]],
    critters: [['bird', 4], ['fish', 2]],
    particles: [[0xffffff, 0xd8f0ff], -0.2, 4],
    patches: [
      { name: 'The harbour', shape: 'blob', center: true, rFrac: 0.5, water: 0x3a9ec9, dead: 0x4e5258, alive: 0x5a8aa0, props: [['tugboat', 0.01, 'inner'], ['buoy', 0.02, 'inner'], ['bollard', 0.04, 'rim']], critters: [['fish', 3], ['bird', 2]] },
      { name: 'Container yard', shape: 'blob', ...M, dead: 0x5e626a, alive: 0xb8c4cc, pave: 1, props: [['container', 0.08]] },
      { name: 'The quay', shape: 'path', dead: 0x60646c, alive: 0xb0bcc4, pave: 1, props: [['bollard', 0.08, 'rim'], ['crane', 0.008, 'rim']] },
      { name: 'Lighthouse point', shape: 'blob', ...S, dead: 0x5a5e66, alive: 0xc8ccd0, props: [['lighthouse', 0.03, 'inner']] },
      { name: 'Fish market', shape: 'blob', ...S, dead: 0x62666c, alive: 0xd0d4d8, pave: 1, props: [['stall', 0.05]] },
      { name: 'Little mooring', shape: 'blob', ...S, water: 0x4ab0d0, dead: 0x50545a, alive: 0x6a98a8, props: [['buoy', 0.06, 'inner']], critters: [['fish', 1]] },
    ],
    patchCount: 9,
    finds: [['🐟', 'Sardine', 'c'], ['⚓', 'Anchor', 'c'], ['🦐', 'Shrimp', 'c'], ['🧢', 'Sailor cap', 'c'], ['🧭', 'Compass', 'r'], ['🚢', 'Model ship', 'r'], ['🦞', 'Lobster', 'r'], ['🐳', 'Friendly whale', 'l']],
  },
});


// ---------------------------------------------------------------- Skyhaven galaxy
// Grassy islands drifting in a sea of cloud. style[4] = cloud: low ground between the islands
// becomes cloud sea, grey and stormy until restored, then soft sunlit white.

Object.assign(BIOMES, {
  pastures: {
    name: 'Cloud Pastures', creature: 'sheep', weight: 0.12, terrain: 'islands',
    dead: 0x6a6e66, alive: 0x8ee07a, sky: ['#9cc8ff', '#fff2d8'], style: [0, 0, 0, 0, 1],
    small: [['grass', 0.12], ['bluebell', 0.03], ['cloudPuff', 0.002]],
    big: [['shepherdHut', 0.002]],
    critters: [['butterfly', 3], ['bird', 2]],
    particles: [[0xffffff, 0xfff6e0], -0.3, 5],
    patches: [
      { name: 'Sheep fold', shape: 'blob', ...M, dead: 0x666a5e, alive: 0x9ae684, props: [['stoneWall', 0.06, 'rim'], ['grass', 0.3]], critters: [['butterfly', 1]] },
      { name: 'Dry-stone lane', shape: 'path', dead: 0x7e7a72, alive: 0xd8d0bc, props: [['stoneWall', 0.06, 'rim'], ['stile', 0.015, 'rim']] },
      { name: 'Bluebell bank', shape: 'blob', ...M, dead: 0x5e6260, alive: 0x86d47a, props: [['bluebell', 0.45]], critters: [['bee', 2]] },
      { name: "Shepherd's hut", shape: 'blob', ...S, dead: 0x6a665e, alive: 0x9ade80, props: [['shepherdHut', 0.035, 'inner'], ['bluebell', 0.15]] },
      { name: 'Cloud nursery', shape: 'blob', ...S, dead: 0x6e7074, alive: 0xe8f0ff, props: [['cloudPuff', 0.12]] },
      { name: 'Clover hill', shape: 'blob', ...L, dead: 0x62665a, alive: 0x7cd468, props: [['grass', 0.3], ['flower', 0.05]] },
    ],
    patchCount: 10,
    finds: [['🧶', 'Ball of wool', 'c'], ['🔔', 'Sheep bell', 'c'], ['🧀', 'Cheese wheel', 'c'], ['🍞', 'Fresh loaf', 'c'], ['🧣', 'Knitted scarf', 'r'], ['🎐', 'Wind chime', 'r'], ['🥾', 'Hiking boot', 'r'], ['☀️', 'Bottled sunshine', 'l']],
  },
  cliffs: {
    name: 'Windmill Cliffs', creature: 'goat', weight: 0.04, terrain: 'cliffs',
    dead: 0x6c6a70, alive: 0xa6d884, sky: ['#88b8f8', '#ffe8cc'], style: [0, 0, 0, 0, 1],
    small: [['grass', 0.08], ['flower', 0.02]],
    big: [['windmill', 0.0018], ['cliffRock', 0.004]],
    critters: [['bird', 4]],
    particles: [[0xffffff, 0xe8f4ff], -0.2, 6],
    patches: [
      { name: 'Windmill hill', shape: 'blob', center: true, rFrac: 0.3, dead: 0x6a6866, alive: 0xb0dc88, props: [['windmill', 0.012, 'inner'], ['flower', 0.2]] },
      { name: 'Rope bridge', shape: 'path', dead: 0x7a7270, alive: 0xd0b48a, props: [['ropeBridge', 0.05]] },
      { name: 'Kite ridge', shape: 'blob', ...M, dead: 0x666468, alive: 0x9cd480, props: [['kite', 0.05], ['grass', 0.2]] },
      { name: 'Rock stacks', shape: 'blob', ...M, dead: 0x6a6870, alive: 0xc8c0d0, props: [['cliffRock', 0.06]] },
      { name: 'Goat track', shape: 'path', dead: 0x76726e, alive: 0xd8ccb0, props: [['pathStone', 0.1], ['stoneWall', 0.02, 'rim']] },
      { name: 'Wildflower ledge', shape: 'blob', ...S, dead: 0x666266, alive: 0xa8e08c, props: [['flower', 0.4], ['bluebell', 0.1]], critters: [['butterfly', 2]] },
    ],
    patchCount: 9,
    finds: [['🌾', 'Wheat sheaf', 'c'], ['🪨', 'Cliff pebble', 'c'], ['🌬️', 'Breeze in a jar', 'c'], ['🍃', 'Windblown leaf', 'c'], ['⛰️', 'Summit stone', 'r'], ['🎏', 'Carp streamer', 'r'], ['🪂', 'Parachute', 'r'], ['🌪️', 'Tame tornado', 'l']],
  },
  rainbow: {
    name: 'Rainbow Falls', creature: 'unicorn', weight: 0.06, terrain: 'islands',
    dead: 0x686670, alive: 0x9adcc8, sky: ['#b0a8ff', '#ffe0f0'], style: [0, 0, 0.2, 0, 1],
    small: [['rainbowFlower', 0.03], ['grass', 0.06]],
    big: [['rainbowArch', 0.0015], ['prism', 0.003]],
    critters: [['butterfly', 4], ['dragonfly', 2]],
    particles: [[0xffb8dc, 0xfff0a0, 0xa8ecd6, 0xb4dcff, 0xd8c8ff], -0.4, 8],
    patches: [
      { name: 'Rainbow pool', shape: 'blob', center: true, rFrac: 0.4, water: 0x8fd8f0, dead: 0x5e6068, alive: 0x7ccab8, props: [['waterfallRock', 0.02, 'rim'], ['lily', 0.05, 'inner']], critters: [['fish', 2], ['dragonfly', 2]] },
      { name: 'Rainbow arch', shape: 'blob', ...S, dead: 0x6a6872, alive: 0xc8e8e0, props: [['rainbowArch', 0.03, 'inner'], ['rainbowFlower', 0.2]] },
      { name: 'Prism grotto', shape: 'blob', ...M, emissive: 0.25, dead: 0x5e5c68, alive: 0xc0b0e8, props: [['prism', 0.08]] },
      { name: 'Waterfall steps', shape: 'path', dead: 0x666670, alive: 0xa8d8d0, props: [['waterfallRock', 0.03, 'rim']] },
      { name: 'Painted meadow', shape: 'blob', ...L, dead: 0x62626a, alive: 0x9ce0b0, props: [['rainbowFlower', 0.35]], critters: [['butterfly', 2]] },
      { name: 'Misty spring', shape: 'blob', ...S, water: 0xa8e4f8, dead: 0x5a5c64, alive: 0x88d0c0, props: [['lily', 0.1, 'inner']] },
    ],
    patchCount: 10,
    finds: [['💧', 'Water droplet', 'c'], ['☂️', 'Umbrella', 'c'], ['🎨', 'Paint palette', 'c'], ['🖍️', 'Crayon', 'c'], ['💎', 'Prism gem', 'r'], ['🔮', 'Crystal ball', 'r'], ['🪄', 'Magic wand', 'r'], ['🌈', 'Rainbow in a jar', 'l']],
  },
  balloons: {
    name: 'Balloon Meadow', creature: 'eagle', weight: 0.1, terrain: 'islands',
    dead: 0x6a6c62, alive: 0x92dc76, sky: ['#94c4ff', '#ffecc8'], style: [0, 0, 0, 0, 1],
    small: [['grass', 0.1], ['flower', 0.03]],
    big: [['hotAirBalloon', 0.001]],
    critters: [['bird', 3], ['butterfly', 2]],
    particles: [[0xffffff, 0xffe8b0], -0.3, 5],
    patches: [
      { name: 'Launch field', shape: 'blob', center: true, rFrac: 0.3, dead: 0x6a6a60, alive: 0xa0e080, props: [['hotAirBalloon', 0.012, 'inner'], ['windsock', 0.02, 'rim']] },
      { name: 'Picnic spot', shape: 'blob', ...S, dead: 0x666860, alive: 0x96dc7c, props: [['picnicBlanket', 0.05, 'inner'], ['flower', 0.2]], critters: [['bee', 2]] },
      { name: 'Weather station', shape: 'blob', ...S, dead: 0x6c6a66, alive: 0xd0dcc0, props: [['weatherVane', 0.04, 'inner'], ['windsock', 0.03, 'rim']] },
      { name: 'Kite field', shape: 'blob', ...M, dead: 0x64665e, alive: 0x8cd474, props: [['kite', 0.06], ['grass', 0.2]] },
      { name: 'Hedgerow path', shape: 'path', dead: 0x787468, alive: 0xd8cca8, props: [['bush', 0.04, 'rim'], ['flower', 0.1, 'rim']] },
      { name: 'Wildflower field', shape: 'blob', ...L, dead: 0x62645c, alive: 0x9ae080, props: [['flower', 0.35], ['bluebell', 0.1]], critters: [['butterfly', 2]] },
    ],
    patchCount: 10,
    finds: [['🍓', 'Strawberries', 'c'], ['🥪', 'Sandwich', 'c'], ['🧃', 'Juice box', 'c'], ['🍋', 'Lemon', 'c'], ['🗺️', 'Sky map', 'r'], ['🎩', "Balloonist's hat", 'r'], ['🍰', 'Picnic cake', 'r'], ['🪶', 'Golden feather', 'l']],
  },
  stargazer: {
    name: "Stargazer's Peak", creature: 'owl', weight: 0.02, terrain: 'peaks',
    dead: 0x5e5c6a, alive: 0x9a9cd8, sky: ['#4c4890', '#f0b8e0'], style: [0, 0.3, 0.6, 0, 1],
    small: [['moonflower', 0.02], ['glowStone', 0.004]],
    big: [['observatory', 0.0005], ['starLantern', 0.002]],
    critters: [['firefly', 6], ['moth', 2]],
    particles: [[0xfff3a0, 0xd8c8ff, 0xffffff], -0.15, 6],
    patches: [
      { name: 'Observatory', shape: 'blob', center: true, rFrac: 0.28, dead: 0x5a5866, alive: 0xb8b4e0, props: [['observatory', 0.012, 'inner'], ['starLantern', 0.03, 'rim']] },
      { name: 'Telescope terrace', shape: 'blob', ...M, dead: 0x5e5c68, alive: 0xa8a8dc, props: [['telescope', 0.05]] },
      { name: 'Lantern trail', shape: 'path', emissive: 0.2, dead: 0x5a5866, alive: 0xb0a8e0, props: [['starLantern', 0.04, 'rim']], critters: [['firefly', 2]] },
      { name: 'Sundial lawn', shape: 'blob', ...S, dead: 0x62606a, alive: 0x9ca8d8, props: [['sundial', 0.04, 'inner'], ['moonflower', 0.15]] },
      { name: 'Moonflower bed', shape: 'blob', ...M, dead: 0x5c5a66, alive: 0x8c90d8, props: [['moonflower', 0.35]], critters: [['moth', 1]] },
      { name: 'Star-chart circle', shape: 'blob', ...S, emissive: 0.3, dead: 0x5a586a, alive: 0xc0b8f0, props: [['glowStone', 0.1]] },
    ],
    patchCount: 9,
    finds: [['⭐', 'Wishing star', 'c'], ['🌙', 'Crescent moon', 'c'], ['🕯️', 'Candle', 'c'], ['📜', 'Star chart', 'c'], ['🔭', 'Telescope', 'r'], ['🪐', 'Ringed planet', 'r'], ['☄️', 'Comet', 'r'], ['🌌', 'Milky Way', 'l']],
  },
});

export const BIOME_IDS = Object.keys(BIOMES);
